### ISSUE TITLE
Add registration fee to the website

### ISSUE THREAD

**Issue by gmcharlt** [code4lib/2018.code4lib.org#129]
Per the announcement at https://lists.clir.org/cgi-bin/wa?A2=CODE4LIB;61c15b00.1711, please update the website to reflect the following

- that the registration fee for the main conference is USD$350
- that registration for the pre-conference workshop day is USD$60, and covers either a full-day session or two half-day sessions
- that a "plus one" rate of $40 is available for folks accompanying attendees who wish to partake of food and meals offered by the conference
- that registration will open at noon EST on 6 December 2017

Thanks!

**Comment by phette23** [comment]
I'm on it!

**Comment by phette23** [comment]
@gmcharlt my PR #130 is addressing this & should be merged soon

**question**: last year the site also had some details about the registration system (see ["additional information"](http://2017.code4lib.org/attend/))—will those be the same? Should I copy over the same text? For now I've chosen not to include them as they seem very specific.

**Comment by gmcharlt** [comment]
We're still deciding about whether/how to stage the registration waves, so the first two additional points from the 2017 page shouldn't be brought over.  However, the fourth point can be (preconference workshops can be selected during registration) as can the third point once accepted talks are put on the website.
