### ISSUE TITLE
Preconference info / text contrast with the hero img

### ISSUE THREAD

**Issue by queryluke** [code4lib/2018.code4lib.org#17]
We currently show announcements about registration, voting, proposals, etc in 2 places:

1. The timeline page `./schedule/timeline.html`, which is linked to from the "What's going on" button on the homepage
2. The homepage additionally lists any activities.

One issue is the list on the homepage is difficult to notice due to the background image.

What are people's thoughts? Any ideas, examples for improvements?

**Comment by kaitlinnewson** [comment]
For 2, are you referring to where it says (currently) "Sponsorship", under the "What's Going On?" button? Or would the homepage have something listed elsewhere?

I think the "What's Going On" button is great, but maybe could be made more prominent (e.g. larger font size, better contrast, etc.)

**Comment by queryluke** [comment]
Yes, I mean the section that currently only has "Sponsorship". It fills up with a list of activities.

**Comment by phette23** [comment]
Some ideas (not that any are good):

- we could get rid of the list, hoping that people click the "what's going on" button to find out what's up
- we could add a background or incorporate the list into the button above (probably makes it an awkward shape)
- we could do a banner beneath the main menu for the list

I'm not thrilled about any of these. Our main alternative is probably just finding a different hero image that has better contrast. I really like the one we have (and its color palette) but it is a bit tricky to work with.

**Comment by kaitlinnewson** [comment]
I find the free text below the button looks a little awkward, but that's just me, and maybe because there's just one item there right now.

**Comment by phette23** [comment]
My vote is moving towards removing this text entirely since it simplifies our theming and we don't lose much. When other rather important things are happening (e.g. the live stream) they appear as buttons anyways.

**Comment by queryluke** [comment]
Since we've gone live, I agree with @phette23. Let's remove it for now, and, perhaps a better solution will come to us in the nearer future.

I'll leave this issue open for people to comment and/or submit new ideas.

**Comment by phette23** [comment]
From our mtg today: fade the colors in the image a bit to help with this

**Comment by phette23** [comment]
Going to close this given the new `#conferenceInfo` style. Text/img contrast is great now and we have a place to put more buttons or text if need be.
