### ISSUE TITLE
Accessibility: daily schedule page - clock images

### ISSUE THREAD

**Issue by ranti** [code4lib/2018.code4lib.org#179]
Speaker list page has some potential accessibility issue: the clock images don't have alt-text associated with it. 
http://2018.code4lib.org/schedule/day-1/
http://2018.code4lib.org/schedule/day-2/
http://2018.code4lib.org/schedule/day-3/

Suggested fix: put empty alt tag because we also have the hours listed next to the presentation title

**Comment by phette23** [comment]
I followed your recommendation & added a blank alt attribute to all the clock faces in PR #188—does that resolve this?

**Comment by ranti** [comment]
I think that should be sufficient. Thanks.

**Comment by ranti** [comment]
PR #188 merged
