### ISSUE TITLE
Update site title

### ISSUE THREAD

**Issue by wickr** [code4lib/2018.code4lib.org#18]
Since this is the conf. site I'd suggest changing the site title from:
`code4lib - Washington, D.C. 2018`
to
`code4lib 2018 - Washington, D.C.`

**Comment by wickr** [comment]
I guess it had that form for 2017. I think having the year earlier reads better (at least it's how I think of the confs).

**Comment by phette23** [comment]
Yeah that makes sense to me too, submitted a pr just now
