### ISSUE TITLE
Several talks are displaying a date of March 8th

### ISSUE THREAD

**Issue by ghost** [code4lib/2018.code4lib.org#183]
eg, http://2018.code4lib.org/talks/deep-learning-and-historical-collections

**Comment by phette23** [comment]
I see you fixed this in PR #186 but it'd be great for us to use date data rather than this series of conditions which will need to be updated every year.

**Comment by queryluke** [comment]
Yeah, that's a silly piece of logic that I probably wrote, I can clean that up.
