### ISSUE TITLE
Add "contact" or "report a problem" link in the footer

### ISSUE THREAD

**Issue by ghost** [code4lib/2018.code4lib.org#184]
Should we add some kind of instruction for submitting issues?  Perhaps a  basic option would be to link to a repo wiki page with instructions that say to create a repo issue?

**Comment by ghost** [comment]
Rather than ask everyone to have a GitHub account, LPC would like to add an email link instead to code4lib@concentra-cms.com, our conference planning service, who will triage, respond, and forward as necessary.

**Comment by phette23** [comment]
I worded it as "Contact Us" since I think that's broader than "Report a Problem" and might catch some general inquiries.
