### ISSUE TITLE
Hero Image

### ISSUE THREAD

**Issue by queryluke** [code4lib/2018.code4lib.org#2]
Creative commons or owned by us

**Comment by egrguric** [comment]
Possible image, CC BY 2.0 license: https://www.flickr.com/photos/photographingtravis/14988543758/ Thoughts?

**Comment by kaitlinnewson** [comment]
The LoC has some nice shots available, e.g.: http://www.loc.gov/pictures/resource/highsm.03185/

Do we want to try for something exterior though, to match the photos from the last two years?

**Comment by egrguric** [comment]
That's a great image! I think it's okay to go with an interior shot. If we want to go with an exterior shot, how about this one: http://www.loc.gov/pictures/resource/thc.5a51001/ (imagine it artistically cropped)?

**Comment by mcalsada** [comment]
I agree that the interior shot is good. When I think of LoC the [Jefferson reading room](https://flic.kr/p/ciS3Ch) is the first image that pops in my head and not of the outside of the building. If we are going to focus on an exterior shot and want it to be of LoC I have a [picture](https://www.flickr.com/photos/mattcal/908872066/in/album-72157600532557829/) during ALA 2007, but full disclaimer, I'm not a photographer.

**Comment by phette23** [comment]
I like the idea of an interior image too, we certainly don't need to stick with outdoors shots every year. Either the original Flickr image or reading room shot are my favorites.

**Comment by phette23** [comment]
I tried out the reading room and internal LoC images today and I think inside the LoC will work best. We can switch later if people disagree but I'm going to put in a PR for this shortly.
