### ISSUE TITLE
Idea for "welcome to washington" section

### ISSUE THREAD

**Issue by queryluke** [code4lib/2018.code4lib.org#21]
This popped into my head and wanted to notate it for discussion before I forgot.

In the "Welcome to Washington, D.C." section, perhaps we can provide links to non-conference activities/sites/information relating to the conference location?

**Comment by phette23** [comment]
From our meeting last week, the activities committee is going to help provide us with content for this.

**Comment by phette23** [comment]
Guessing we don't have the time to do this :)
