### ISSUE TITLE
New pre-conference times and locations

### ISSUE THREAD

**Issue by Otterfan** [code4lib/2018.code4lib.org#230]
We've had some changed pre-conference locations, and they've all changed times:

**Changed locations**

- Introduction to Spotlight > Moved to Tenley-Friendship Neighborhood Library
- An Introduction to OpenRefine > Moved to Mt. Pleasant Neighborhood Library
- Building Open: Integrating Open Source Discovery Tools with Summon and Alma > Moved to Mt. Pleasant Neighborhood Library

**Time changes**

All AM workshops are now 9:30am - 12:30pm
All PM workshops are now 2:30pm - 5:30pm

Here's a ~~Sheet~~ with the latest list of workshops, locations, and presenters.

Edit: this is a [better Sheet link](https://docs.google.com/spreadsheets/d/1MzqRYNF49Xv1T040Pw2w9pENRgcxhEhs95AGO9tYtpM/edit?usp=sharing)

**Comment by phette23** [comment]
Do we have rooms for the workshops that are now in the neighborhood libraries?

**Comment by Otterfan** [comment]
All we have for a room name is "Meeting Room". The libraries we're in all have one "meeting room" (as opposed to "conference room"), so "Meeting Room" should be enough.

**Comment by phette23** [comment]
Ah OK that's fine, I can fill that in.

**Comment by Otterfan** [comment]
Also, all-day events are now 9:30am to 5:30pm.
