### ISSUE TITLE
Four more pre-conference updates

### ISSUE THREAD

**Issue by Otterfan** [code4lib/2018.code4lib.org#237]
We have a few more corrections to the pre-conference list:

* ~~**Getting Started Visualizing your loT Data in Tableau** > change time to _All-day_ session, not _AM_~~
* **ARIA Basics: Making your Web Content…** > Change location to Omni Shoreham Hotel : Senate Forum Room
* **Spark in the Dark 101** > Change location to Omni Shoreham Hotel : Senate Forum Room
* **Digital Empathy: Creating Safe Spaces Online** > Change location to West End Library : Meeting Room

The full list of workshops is [available as a Sheet](https://docs.google.com/spreadsheets/d/1MzqRYNF49Xv1T040Pw2w9pENRgcxhEhs95AGO9tYtpM/edit?usp=sharing).

**Comment by Otterfan** [comment]
I've just heard that there might be an issue with the Tableau workshop (AM > All-day), so should hold off on changing that one.

**Comment by queryluke** [comment]
What is the recency of that sheet? Last week I moved "Learn Tech to Teach Tech" to CUA campus, but now it's back in the Council Room?

**Comment by queryluke** [comment]
I guess a better question: is the sheet you've provided the official sheet of locations and times? If so, I'll just make sure the information in it matches the information in the data files.

**Comment by Otterfan** [comment]
This should be the same sheet from #230 last week. This is a copy of the official sheet, which is [here](https://docs.google.com/spreadsheets/d/1LHFkOHMepFSZkFdcCdj4Rx4qOEoBU6A0rnSXF07IIZw/edit?usp=sharing), but with some data pared out. If you can't access the official list send me a message on Slack.

Learn to Teach Tech should definitely be in the Omni. Do you have an issue for where the change to CUA was made? I'd like to check against it.

**Comment by Otterfan** [comment]
Nevermind, I see it in #222. I'll check those. Do you have the source data for that?

**Comment by queryluke** [comment]
Just sent you an IM. I'll get started on making the site reflect what's in your sheet.

**Comment by queryluke** [comment]
Do you want me to also put links to these addresses, for the locations?
