### ISSUE TITLE
HTML & CSS clean-up

### ISSUE THREAD

**Issue by queryluke** [code4lib/2018.code4lib.org#24]
There are a lot of unnecessary classes and and div nesting.

Also, I want to get rid of `.cell .cell-lg` as bootstrap already has built-in container functionality.

**Comment by queryluke** [comment]
Also should clean up the `<h#>` tags and page structure.

Write a wiki about layouts for future pages

**Comment by egrguric** [comment]
@queryluke, I can help with this too if you want to trade off a specific section.

**Comment by queryluke** [comment]
thanks! Anyone can tackle the `<h#>` tags. But I'll need to do some trial and error with the `.cell` class.
