### ISSUE TITLE
Fix workshop times

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2018.code4lib.org#253]
I was just looking at the workshop schedule and noticed they all say 9:30 - 5:30.

**Comment by queryluke** [comment]
on it, that's probably something i did

**Comment by Otterfan** [comment]
Ben from the Pre-conference group here to piggyback on this.

We spoke with reps from the two all-day workshops yesterday, and they would like to stay 9a - 5p:

- IIIF Hands-on Technical Workshop
- Learn Tech to Teach Tech
