### ISSUE TITLE
Change all-day workshop times

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2018.code4lib.org#256]
From comment by @Otterfan on #253:

We spoke with reps from the two all-day workshops yesterday, and they would like to stay 9a - 5p:

IIIF Hands-on Technical Workshop
Learn Tech to Teach Tech

**Comment by queryluke** [comment]
@Otterfan Is this just a change from 9:30 - 5:30 > 9 - 5

**Comment by Otterfan** [comment]
Yep, just those two workshops should be changed to 9a - 5p

**Comment by Otterfan** [comment]
We also have two more issues related to pre-con stuff to add (one completely changed workshop and two workshops swapping location). I'll add those and cross-reference them here.

**Comment by Otterfan** [comment]
The other pre-con issues are #257 and #258.
