### ISSUE TITLE
Add food menus

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2018.code4lib.org#283]
From slack:

This is the format last year - http://2017.code4lib.org/schedule/food/day1-menus.html#Breakfast. Here is the current listing of menus and ingredients - https://docs.google.com/document/d/1oa8613AN3ed4OMCyzlW0SzywxcjeRZQtKRC4gJVzw9g/edit?usp=sharing. There are some ingredients missing, but most of the info is here.

**Comment by mcalsada** [comment]
@phette23 pushed #280 yesterday.We don't have the indicators for Vegan, Vegetarian, or GF but I think we need input from the venue to do that.

**Comment by kaitlinnewson** [comment]
Sorry for the mix up!
