### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by queryluke** [code4lib/2018.code4lib.org#3]
Based on main photo or location

**Comment by phette23** [comment]
Library of Congress blue: #00618e

**Comment by egrguric** [comment]
Also, 
LOC header blue: #046390
LOC header orange: #ffa500

**Comment by queryluke** [comment]
See my notes in #9 , once that is merged, it should be easier to play with the theme colors

**Comment by queryluke** [comment]
Colors based on the image:
https://coolors.co/12192d-94acc9-f6fdfd-f65108-b41403

Red, White, and Blue. Based on LOC blue
https://coolors.co/121f2d-00618e-f4fcfa-f41307-b5031e

Blue and Orange, based on LOC Blue and Orange
https://coolors.co/003542-00618e-fcf9ef-ffa500-ea6d00

Thoughts?

**Comment by kaitlinnewson** [comment]
Personally I really like the color palette based on the image

**Comment by phette23** [comment]
Yeah, I like the image one as well. The blue/orange scheme also would work well I think, those yellow/orange colors from last year were effective.

**Comment by queryluke** [comment]
Made a branch [theme-option-image](https://github.com/code4lib/2018.code4lib.org/tree/theme-option-image) which utilizes the colors of my first link. Everything should meet WCAG AA standards in terms of contrast.

The only main issue is the red "what's going on" button. The dark blue stands out against that background, but I think the red button looks nicer throughout the rest of the site. I hope solving #17 will make the washed red button a moot point.

**Comment by phette23** [comment]
+1 to this theme.

**Comment by queryluke** [comment]
I'll make a few minor changes and submit a pr soon
