### ISSUE TITLE
new "adamantium" sponsor level needs badge icon

### ISSUE THREAD

**Issue by phette23** [code4lib/2018.code4lib.org#30]
see PR #29 — there's a new top level of sponsorship which doesn't have an icon yet

**Comment by queryluke** [comment]
Did they say if it should be indicative of wolverine?

**Comment by phette23** [comment]
Oh I think so 🐺  ❌

**Comment by phette23** [comment]
I'm going to work on this one by incorporating this Wolverine claw icon into the badges.svg file: https://thenounproject.com/search/?q=wolverine&i=52605
