### ISSUE TITLE
Add breakout sessions and lightning talks

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2018.code4lib.org#301]
Good to have for reference. We could probably list them all on a single page and link out to them from the schedule.

**Comment by kaitlinnewson** [comment]
Day 1 breakout sessions:

Ex Libris and Open Source Discovery Data Warehousing/Privacy
Expanding the Code of Conduct to online spaces (notes: https://docs.google.com/document/d/1s3TT5tUFiHhR5fBD7VutwLWHETgnMo7aa8Zw0xYwveM/edit)
Fedora Test API
Teaching Beginners: How to be Better
Poor Man's VDI with LTS & Drupal
LibDevOps
ArchiveSpace Core Committees and Community development
Data4Lib/Spark in the Dark/Big Data
ETD Submittal
FOLIO SWORDS (real swords)

**Comment by tomkeays** [comment]
I wished we had done this last year. In the past, the wiki was the place to go for signing up and documenting lightning talks and breakouts, but that was kind of a fail last year. It makes sense to add them to the website -- a single place to look to learn about the conference -- even if they have to be added after the fact. Links to Google docs and gists seems adequate.

**Comment by kaitlinnewson** [comment]
Day 1 Lightning Talks:
(OSF slides added as they become available, but I've documented the slide links where I could in case we need them)

For the love of standards - Josh Weisman (slides: https://docs.google.com/presentation/d/1vrwtQYTxkMxRtYh4RjtulKaLM-LVUOwYj4riUV8zEIQ/edit)
Using Glitch to Make Apps with Library Collections - Laura Wrubel (https://osf.io/gkfzh/)
Enhancing Library Discovery with Linked Open Data - Steve Meyer (slides: https://web.library.wisc.edu/sp/c4l18/#/intro)
Using JIRA to manage archives workflows - Maggie Hughes (slides: goo.gl/UV8tU5)
Critical Mass Accessibility - Kate Deibel (https://osf.io/um7sn/)
Omeka turns 10! - Patrick Murray-John (no slides)
Working with MARC: An outsider's perspective - Mattie Schraeder (no slides)
FOLIO Innovation Challenge - Andrew Nagy
TagTeam: Social Tagging on Open Platforms - Kelly Fitzpatrick (https://osf.io/y75zf/)
indieweb + code4lib = <3 - Mark Matienzo
Code4lib Social - Francis Kayiwa (single slide)
Teaching Programming for Libraries/Librarians: Where the crap are the textbooks? - Elizabeth Wickes

**Comment by ranti** [comment]
Day 1 Lightning Talks

Josh Weisman @joshmweisman - For the Love of Standards. 
See:   https://developers.exlibrisgroup.com/standards 
Slides: https://docs.google.com/presentation/d/1vrwtQYTxkMxRtYh4RjtulKaLM-LVUOwYj4riUV8zEIQ/edit

Laura Wrubel @liblaura -  Making Glitch to Make Apps with Library Collections. 
See https://glitch.com/@blprnt 
Slides: https://osf.io/gkfzh/ 

Steve Meyer @steve_e_meyer - Enhancing Library Discovery with Linked Open Data. 
Slides: https://tinyurl.com/c4l18-smeyer 

Maggie Hughes - Using JIRA to manage archives workflows. 
See  https://goo.gl/UV8tU5. 
Slide: https://osf.io/w3pjr/ 

Kate Deibel @metageeky - Critical Mass Accessibility. 
Slide: https://osf.io/um7sn/ 

Patrick Murray-John @patrick_mj - Shout out to Omeka users and those who participate in it one way or another. 
See https://omeka.org 
No slides

Mattie Schraeder @frozensolidone - Working with MARC: an outsider’s perspective. 
See https://github.com/frozen-solid/CSharp_MARC 
No slides

Andrew Nagy @asnagy - FOLIO Innovation Challenge. 
See https://www.ebsco.com/folio-innovation-challenge  

Kelly Fitzpatrick @freifraufitz - Tag Team: Social Tagging on Open Platforms. 
See http://tagteam.harvard.edu 
Slide: https://osf.io/y75zf/ 

Mark Matienzo @anarchivist - indieweb + code4lib = <3 . 
See https://indieweb.org 
Slide: https://matienzo.org/storage/2018/2018Feb-code4lib.pdf

Francis Kayiwa @kayiwa - Code4lib Social. 
See https://code4lib.social 
Single slide

Elizabeth Wicker @elliewix - Teaching Programming for Libraries/Librarians: Where the crap are the textbooks? 
Slide: https://osf.io/78fms/

**Comment by ranti** [comment]
Day 2 Breakout Sessions:

Sustainable Development
Continuing Conversation on Website Accessibility / Library Accessibility Community
Hiring & Onboarding
Teaching Beginners, Redux
Software + Data + Library Carpentry: how to get started and what it is
AI/ML/DL (Artificial Intelligence, Machine Learning, Deep Learning)
Spotlight

**Comment by kaitlinnewson** [comment]
Day 2 Lightning talks:

Serendipitous Browsing with VR - Declan Fleming @declan
Video (MP4): https://drive.google.com/file/d/1cCNsZmEpmsADEDAzvLBtHvn7TMLVzUXR/view?usp=sharing
Video (youtube): https://www.youtube.com/watch?v=BxKfSYCCYdk

Algorithmic Awareness and Digital Literacy - Jason Clark @jaclark
Slide: https://www.lib.montana.edu/~jason/talks/algorithmic-awareness-talk-code4lib2018.pdf
Slide at OSF: https://osf.io/dcr3n/ 

FOLIO: Under the Hood - Kurt Nordstrom
Slide: https://osf.io/jer3d/ 

"Who?" Considerations for User Consultation & Testing - Jessica Whu
Slide: https://osf.io/pzc7e/

Automating Circulation Notices in Voyager - Bruce Orcutt @cherveny
See: https://github.com/cherveny/autocirc 
Slide: https://osf.io/z9f7h/

Emoji Curation - Esmé Cowles @escowles
Slide: https://osf.io/dph8e/

Poor Man's VDI - Stephen Gaines
Slide: https://osf.io/s2czv/

A DIY Strategy for Data Recovery of 5.25" floppy disks - David Tenenholtz @DavidTenenholtz
Slide: https://osf.io/zrx2e/ 

Github for Small Teams - Elizabeth Mumpower
Slide: https://osf.io/fsw4r/

LC Labs - 5 months, 3 things - Meghan Ferriter @MeghaninMotion
See: https://labs.loc.gov

On the Road to Find Out: Meetup.com and learning to code - Esther Jackson @EstherWords
Slide: https://docs.google.com/presentation/d/13o3vgXBAjKwjDkPgInPyEPqa68AvkDgEX4PjnZxdDxo/edit#slide=id.g31df613b11_0_5

**Comment by ranti** [comment]
Day 2 Lightning talks (via slack/mjingle)

Lightning Talks – Thursday
Serendipitous Browsing with VP - Declan Fleming
Algorithmic Awareness and Digital Literacy - Jason Clark
FOLIO: Under the Hood - Kurt Nordstrom
"Who?" Considerations for User Consultation & Testing- Jessica Whu
Automating Circulation Notices in Voyager
Emoji Curation - Esmé Cowles
Poor Man's VDI - Stephen Gaines
A DIY Strategy for Data Recovery of 5.25" floppy disks - David Tenenholtz
Github for Small Teams - Elizabeth Mumpower
LC Labs - 5 months, 3 things - Meghan Ferriter
On the Road to Find Out: Meetup.com and learning to code - Esther Jackson

**Comment by kaitlinnewson** [comment]
Day 3 Lightning talks:

Hosting Regional code4lib – Craig Boman and Melissa Cherry
Slides: https://osf.io/n6ejs/

3rd Party Trackers on Library Websites – Tom Boone
Slides: https://github.com/tomboone/code4lib-lightning-2018

LCC + Borges + MUD = ? – Mauricio Giraldo Arteaga @mgiraldo
Slides: https://osf.io/xwt64/

Preserving Civic Data? Chad Nelson @bibliotechy 
Slides: https://github.com/bibliotechy/bibliotechy.github.com/blob/master/images/future-proofing-civic-data%20real.pptx?raw=true

Conveying Value to  Non-Expert Experts: An Adventure in Law Libraries  -  Laura Chuang @_snarkshow 
Slides: https://osf.io/mrp78/

ArchivesSpace API + Python = :heart: – Bria Parker @bria_parker 
See: https://go.umd.edu/f4q
Slides: https://osf.io/dqzpr/

ISSUES with ISSUES – Shaun Ellis @sdellis 
Slides: https://docs.google.com/presentation/d/1iSBzBYCM8xwy2JZc9fg8tK73Si4SJ7WolFnhH5wxbQg/edit#slide=id.gcb9a0b074_1_0

Leveraging Docker for a  Dev Experience – Andrew Gearhart @AndrewGearhart
Slides: https://bit.ly/c4l18-docker-lightning-talk

Data Migration and Data Cleaning Must Go Hand in Hand! – Hui Zhang and Ryan Wick @ryanwick
See: https://ir.library.oregonstate.edu/
Slides: https://osf.io/h93y8/ 

code4lib map - Kim Pham
See: https://github.com/code4lib/code4lib-map
Slides: https://osf.io/nhxzs/

**Comment by ranti** [comment]
Created wiki pages, at least for the time being if actual web pages on the conference website are preferred 
https://wiki.code4lib.org/Code4Lib2018_Breakout_Sessions
https://wiki.code4lib.org/Code4Lib2018_Lightning_Talks
