### ISSUE TITLE
Remove Breakfast, Lunch, and Breaks section of the prospectus 

### ISSUE THREAD

**Issue by libraryman** [code4lib/2018.code4lib.org#36]
Could you please remove the Breakfast, Lunch, and Breaks section of the prospectus as we are not offering these targeted sponsorships this year.  Also, could you remove "main reception" under the "targeted sponsorship" section of the prospectus since it appears at the top.

One other change is to change the **contributor** level to $1000- $1499 and supporter to $999 - $250 (while removing the non-monetary) 
Thanks,

Jeffrey 
Sponsorship Committee

**Comment by queryluke** [comment]
closed in #38
