### ISSUE TITLE
Review sponsors page

### ISSUE THREAD

**Issue by queryluke** [code4lib/2018.code4lib.org#4]
Is there a better way to highlight or display sponsors?

**Comment by phette23** [comment]
Idea from mtg: add row to home page of logos like many conferences do. People will add sites to emulate. [E&RL](https://www.electroniclibrarian.org/2017-sponsors/)

**Comment by egrguric** [comment]
Idea from meeting: background

**Comment by phette23** [comment]
Thought on implementing the idea above: we can just loop through whatever very high level (adamantium/diamond/platinum) sponsors we have and display those on the home page.

**Comment by ghost** [comment]
I'm currently working on #71 and it looks like something is already in place.  `_includes/homepage/pre_conference.html` already adds Adamantium and Platinum sponsors to the homepage, though it seems this should be located in a `_includes/homepage/sponsors.html` file and should probably be Adamantium and Diamond sponsors if only the top two are to be displayed.

**Comment by phette23** [comment]
I think with @wallberg-umd's latest PR this issue is settled, we now have sponsor logos on the home page.
