### ISSUE TITLE
Set-up Analytics

### ISSUE THREAD

**Issue by queryluke** [code4lib/2018.code4lib.org#5]

**Comment by phette23** [comment]
As part of this issue, establish a way to hand-down the analytics account each year to the next website working group.

**Comment by phette23** [comment]
After we get the site online I will add everyone on the website group's email addresses to the analytics account.

**Comment by queryluke** [comment]
on the clean slate page, I added a stub for "creating a new Analytics property", which, I guess next year we can fill out when we have an idea of how to hand-down the analytics
