### ISSUE TITLE
General Info: scholarships

### ISSUE THREAD

**Issue by phette23** [code4lib/2018.code4lib.org#52]
Write new content:

- scholarships
- scholarship recipients

**Comment by ranti** [comment]
Assigned to Ranti.

**Comment by phette23** [comment]
The files associated with this content are:

- diversity-scholarships/
  + angel-fund.html
  + index.html
  + recipients.html

**Comment by ranti** [comment]
added content to point to /diversity-scholarships/ section & submitted a pull request

**Comment by ranti** [comment]
(Eric P.) Moved angel-fund.html and recipients.html under /diversity-scholarships/ into /general-info/ ; removed /diversity-scholarships/

(Ranti) Added scholarship content per Scholarship Committee (scholarship.html)
