### ISSUE TITLE
Add basic venue information

### ISSUE THREAD

**Issue by ghost** [code4lib/2018.code4lib.org#60]
Per announcement on the list:

> The conference will take place in Washington's historic Omni Shoreham Hotel<https://www.omnihotels.com/hotels/washington-dc-shoreham>, just a couple blocks from the Woodley Park metro station, walking distance to the National Zoo and bustling Adams Morgan neighborhood.

The Omni has given us permission to reuse any image from their website on our conference site.

I'm not sure what the timeline is for your restructuring in #51 but if not soon it would be nice to get this information on the website before that happens.

**Comment by phette23** [comment]
Also addressed in PR #65

**Comment by phette23** [comment]
More venue information under General Info now.
