### ISSUE TITLE
Test secondary nav layout on mobile

### ISSUE THREAD

**Issue by phette23** [code4lib/2018.code4lib.org#68]
Pages using it right now are General Info and Conduct & Safety.

**Comment by mcalsada** [comment]
I reviewed the pages using ios11/Safari. Secondary nav looked good and everything seemed to work as expected. 

I'd recommend that someone else take a look at the Conduct & Safety page for opnions on these. These 2 things popped out as ok, but may be undesirable.
* The actual code of conduct (and it's headings) seem large (may be a bonus for accessibility) It's also not justified text so it doesn't match up with other content. ![Code of Conduct screenshot](https://i.imgur.com/79Unt1c.png)
* Some of the other content seems to not flow well on the smaller screen. The bullets to separate numbers for the DC PD is being broken up. Maybe `<ul>` would work better to distinguish the 3 numbers?  ![DC Police section screenshot](https://i.imgur.com/hxsl4uN.png)

**Comment by phette23** [comment]
Thanks for the feedback @mcalsada! The conduct/safety section is mine so I'll take a look. I agree that maybe list items would be better than this text separated by middots.

**Comment by phette23** [comment]
I actually think the secondary nav works pretty well on mobile screens. Anybody have other experiences or things we think could be done? I'm ready to close this if not.
