### ISSUE TITLE
Conversation about site navigation/architecture

### ISSUE THREAD

**Issue by queryluke** [code4lib/2018.code4lib.org#7]
Ideas and thoughts about making the site navigation and architecture clearer

**Comment by egrguric** [comment]
**Top Level Nav**

Current:         | Option 1:                   | Option 2:         | Final Version     |
--------------- | ----------------------- | ----------------- | ------------------ |
Home             |  Home *                    | Home               | Home    |
Schedule        | Schedule                  | Schedule         | Schedule (Attend Information) |
Attend            | Speakers                   | Speakers         | Speakers |
Speakers       | General Information   | General Information ** | General Info (subsumes Scholarships, About, Venues) |
Venues          | Sponsors                    | Sponsors                     | Sponsors |
Sponsors       | Safety                        | About Code4Lib          | Safety|
Scholarships | Newcomers
Safety            | About Code4Lib
About 

\* Option 1 Homepage includes:
- "Attend" information before the conference, homepage always displays conference name, date, and address of venue. 
- "Schedule" information during the conference

\** Option 2 General Information is a catch-all linking to other information including "Newcomers" and "Safety"

**Comment by queryluke** [comment]
Last year, before we had a set schedule, we had the "Schedule" link go to a timeline of important dates: http://2017.code4lib.org/schedule/timeline.html So "Schedule" can also be toggled based on when we have a set schedule.

Also, I wonder if "Newcomers" & "Safety" can be links on the homepage we introduce shortly before the conference, rather than having a dedicated nav link.

What I really like is the "catch-all" of General Information. This section can act like a traditional site index with sub-navigation. The idea is that General Info is a collection of information that can be contextually linked to from the other content pages.

**Comment by egrguric** [comment]
Agree re: Newcomers. My only concern with removing Safety from top level is that keeping it a visible priority in a top-level nav is an act of inclusion, particularly for new folks. It states very clearly that safety is a priority for the community that is organizing this conference.

**Comment by mcalsada** [comment]
Re: Newcomers, there could be useful info for a new attendee before the conference and may be a place to include some general safety information to stress the importance of that. The info that Becky stated during opening remarks this year (i.e. how to get the most out of code4lib) is info that I could see being included on the newcomers page. With that said, maybe Newcomers is better served as a link from General Information. 

Re: Safety. It seems that the most important info that is always relevant is the Code of Conduct. Maybe we can include that in the page footer like the [dibi conference](http://www.dibiconference.com/) page. Shortly before/during the conference the info for Duty Officers/Emergency can be toggled on.

**Comment by egrguric** [comment]
That's an excellent point. I'm coming around to thinking that General Info could just have Newcomer and Safety info within it. I love the idea of including Safety info in the footer as well as displaying it elsewhere.

**Comment by phette23** [comment]
> Safety from top level is that keeping it a visible priority in a top-level nav is an act of inclusion, particularly for new folks.

That was my immediate hesistancy with option 2, though I like it a lot more. I wonder if "Conduct" (which was the label for 2016) is actually a better name since conference attendees may be more familiar with codes of conduct than concepts like safety officers, but either way is probably clear enough.

We didn't really do a secondary navigation but I like the idea of Gen Info having a lot underneath it but a secondary nav to assist users. Maybe the sections include Newcomers, Safety, Scholarships, Venues/Transit.

> Last year, before we had a set schedule, we had the "Schedule" link go to a timeline of important dates: http://2017.code4lib.org/schedule/timeline.html

Also note that that's where the schedule link is pointing now and should be one of the first pieces of content we sort out, once we know more about the various dates of activities.

**Comment by phette23** [comment]
Another thing as I'm looking over the site's content "About Code4Lib" is just a hero image and a single paragraph, that doesn't really warrant a top-level nav link. It can be assimilated into something else (the home page?) or have further content added, for instance some of things we're discussing moving under general info like conduct, newcomers, etc.

**Comment by phette23** [comment]
Results of our internal card sort exercise:  https://www.optimalworkshop.com/optimalsort/22v616hl/c4l18/shared-results
