### ISSUE TITLE
open call for scholarship applications 10/16

### ISSUE THREAD

**Issue by phette23** [code4lib/2018.code4lib.org#85]

**Comment by mcalsada** [comment]
@phette23 I will be travelling on 10/16 so won't be able to make this one go. I can try to get a branch/PR set up if we get all the details by Wednesday of how they are accepting applications and any wording. 

This is the [2017 commit](https://github.com/code4lib/2017.code4lib.org/commit/b370750e215398a85ad07b4f89d2936b29b939db#diff-b2a6d4f43b737465fd008c8eb9fbee8d) for opening the call. 

Are we doing a similar thing of adding the call to only the [Scholarships page](http://2018.code4lib.org/general-info/scholarships)? I'm thinking of adding "Scholarships" as a section with a link controlled by a toggle under the "What's going on?" section as well that links back to the scholarship page where the new info about applying will be added. Thoughts?

**Comment by phette23** [comment]
Doing a PR with a note to wait until that date is perfect, I will keep an eye on it and merge on the appropriate date.

Yes, adding to "what's going on" is a very good idea, the sections right now ("proposals" and "voting") don't really encompass this content but we maybe need an "announcements" or "other stuff" category for it. I'll want to do something similar once we know details on the donation matching funds.

**Comment by ranti** [comment]
Call for scholarship page is activated. Keeping the list of sponsorship 'off' until furhter notice.
