### ISSUE TITLE
10/18 edit Angel Fund page to note that donations are accepted

### ISSUE THREAD

**Issue by phette23** [code4lib/2018.code4lib.org#95]
/diversity-scholarships/angel-fund.html notes that donations will start being accepted 10/18 so we should update this page

**note**: we'll be given a link to add to the page, check Slack for it if it's not communicated to us by now

**Comment by ranti** [comment]
(Eric P.) Moved angel-fund.html to /general-info/ ; removed /diversity-scholarships/
